version: '3'

services:
  backend:
    build:
      context: .
    entrypoint: /code/entrypoint.sh
    ports:
      - "80:8080"
    restart: always
    volumes:
            #      - /code/jubiler/db.sqlite3
      - .:/code/
        #    depends_on:
        #      - postgres

        #  postgres:
        #    image: postgres:10-alpine
        #    restart: always
        #    environment:
        #            - PGDATA=/var/lib/postgresql/data/db-files/
        #    volumes:
        #      - pg_data:/var/lib/postgresql/data/

        #volumes:
        #    code:
          #  pg_data:
