# Generated by Django 2.0.3 on 2018-05-19 13:06

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInformations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='contents')),
            ],
            options={
                'verbose_name': 'Podstrona: O firmie',
                'verbose_name_plural': 'Podstrona: O firmie',
            },
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('baner', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Strona Główna - Zdjęcie Główne',
                'verbose_name_plural': 'Strona Główna - Zdjęcie Główne',
            },
        ),
        migrations.CreateModel(
            name='MiniSliderOfferEngraving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'Strona Główna - Slajder: Obróbka i grawerowanie',
                'verbose_name_plural': 'Strona Główna - Slajder: Obróbka i grawerowanie',
            },
        ),
        migrations.CreateModel(
            name='MiniSliderOfferIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'Strona Główna -Slajder: Biżuteria na zamówienie',
                'verbose_name_plural': 'Strona Główna - Slajder: Biżuteria na zamówienie',
            },
        ),
        migrations.CreateModel(
            name='MiniSliderOfferRepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'Strona Główna - Slajder: Naprawa i rekonstrukcja',
                'verbose_name_plural': 'Strona Główna - Slajder: Naprawa i rekonstrukcja',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default=0, verbose_name='contents')),
            ],
            options={
                'verbose_name': 'Podstrona: Oferta',
                'verbose_name_plural': 'Podstrona: Oferta',
            },
        ),
        migrations.CreateModel(
            name='ServiceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('title', models.CharField(default=0, max_length=25)),
                ('service', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='service_images', to='slider.Service')),
            ],
            options={
                'verbose_name': 'Podstrona: Oferta - zdjęcia do poszczególnych usług',
                'verbose_name_plural': 'Podstrona: Oferta - zdjęcia do poszczególnych usług',
            },
        ),
    ]
