# Generated by Django 2.0.3 on 2018-04-10 22:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_minisliderofferengraving_minisliderofferindividual_minisliderofferrepair'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInformations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Edytor strony O mnie')),
            ],
            options={
                'verbose_name': 'Strona Główna - Slajder: Grawerowanie',
                'verbose_name_plural': 'Strona Główna - Slajder: Grawerowanie',
            },
        ),
        migrations.AlterModelOptions(
            name='mainslider',
            options={'verbose_name': 'Strona Główna - Zdjęcie Główne', 'verbose_name_plural': 'Strona Główna - Zdjęcie Główne'},
        ),
        migrations.AlterModelOptions(
            name='minisliderofferengraving',
            options={'verbose_name': 'Strona Główna - Slajder: Grawerowanie', 'verbose_name_plural': 'Strona Główna - Slajder: Grawerowanie'},
        ),
        migrations.AlterModelOptions(
            name='minisliderofferindividual',
            options={'verbose_name': 'Strona Główna - Slajder: Na zamówienie', 'verbose_name_plural': 'Strona Główna - Slajder: Na zamówienie'},
        ),
        migrations.AlterModelOptions(
            name='minisliderofferrepair',
            options={'verbose_name': 'Strona Główna - Slajder: Naprawa', 'verbose_name_plural': 'Strona Główna - Slajder: Naprawa'},
        ),
    ]
