# Generated by Django 2.0.5 on 2018-05-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20180519_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutinformations',
            options={'verbose_name': 'Podstrona: O firmie', 'verbose_name_plural': 'Podstrona: O firmie'},
        ),
        migrations.AlterModelOptions(
            name='minisliderofferengraving',
            options={'verbose_name': 'Strona Główna - Slajder: Obróbka i grawerowanie', 'verbose_name_plural': 'Strona Główna - Slajder: Obróbka i grawerowanie'},
        ),
        migrations.AlterModelOptions(
            name='minisliderofferindividual',
            options={'verbose_name': 'Strona Główna - Slajder: Biżuteria na zamówienie', 'verbose_name_plural': 'Strona Główna - Slajder: Biżuteria na zamówienie'},
        ),
        migrations.AlterModelOptions(
            name='minisliderofferrepair',
            options={'verbose_name': 'Strona Główna - Slajder: Naprawa biżuterii', 'verbose_name_plural': 'Strona Główna - Slajder: Naprawa biżuterii'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Podstrona: Oferta', 'verbose_name_plural': 'Podstrona: Oferta'},
        ),
        migrations.AlterModelOptions(
            name='serviceimages',
            options={'verbose_name': 'Podstrona: Oferta - dodawanie zdjęć', 'verbose_name_plural': 'Podstrona: Oferta - dodawanie zdjęć'},
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceimages',
            name='title',
            field=models.CharField(default='title', max_length=25),
        ),
    ]
