# Generated by Django 2.0.3 on 2018-04-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_auto_20180411_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutinformations',
            options={'verbose_name': 'Podstrona O firmie', 'verbose_name_plural': 'Podstrona O firmie'},
        ),
    ]
