# Generated by Django 2.0.3 on 2018-04-10 23:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_auto_20180411_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinformations',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Edytor strony O mnie'),
        ),
    ]
