# Generated by Django 2.0.3 on 2018-05-19 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Produkty',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('product', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='products.MainProducts')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=50)),
            ],
            options={
                'verbose_name': 'Kategorie produktów',
                'verbose_name_plural': 'Kategorie produktów',
            },
        ),
        migrations.CreateModel(
            name='ProductsMini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'Szybka Galeria - 5 zdjęć',
                'verbose_name_plural': 'Szybka Galeria - 5 zdjęć',
            },
        ),
        migrations.AddField(
            model_name='mainproducts',
            name='category',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='category', to='products.ProductsCategory'),
        ),
    ]
