# Generated by Django 2.0.3 on 2018-03-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsMini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
