# Generated by Django 2.0.3 on 2018-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='productsmini',
            options={'verbose_name': 'Galeria produktów - Strona Główna', 'verbose_name_plural': 'Galeria produktów - Strona Główna'},
        ),
        migrations.AddField(
            model_name='mainproducts',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
