# Generated by Django 2.0.3 on 2018-03-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180312_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsmini',
            options={'verbose_name': 'Galeria produktów - Strona Główna', 'verbose_name_plural': 'Galeria produktów - Strona Główna'},
        ),
        migrations.AlterField(
            model_name='productsmini',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
