# Generated by Django 2.0.5 on 2018-05-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180519_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'Zdjęcia Produktu',
                'verbose_name_plural': 'Zdjęcia Produktu',
            },
        ),
        migrations.AlterModelOptions(
            name='productscategory',
            options={'verbose_name': 'Kategorie Produktów', 'verbose_name_plural': 'Kategorie Produktów'},
        ),
        migrations.AlterModelOptions(
            name='productsmini',
            options={'verbose_name': 'Galeria - Wybrane Produkty', 'verbose_name_plural': 'Galeria - Wybrane Produkty'},
        ),
        migrations.RemoveField(
            model_name='mainproducts',
            name='image',
        ),
        migrations.AddField(
            model_name='productsimages',
            name='to_product',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_product', to='products.MainProducts'),
        ),
    ]
