# Generated by Django 2.0.3 on 2018-03-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180314_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
    ]
