# Generated by Django 2.0.3 on 2018-03-18 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productscategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscategory',
            name='product',
        ),
        migrations.AddField(
            model_name='mainproducts',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products_category', to='products.ProductsCategory'),
        ),
        migrations.AlterField(
            model_name='productscategory',
            name='title',
            field=models.CharField(default='title', max_length=50),
        ),
    ]
