# Generated by Django 2.0.3 on 2018-03-18 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180318_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproducts',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_category', to='products.ProductsCategory'),
        ),
    ]
