# Generated by Django 2.0.3 on 2018-03-18 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180318_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproducts',
            name='category',
        ),
        migrations.AddField(
            model_name='productscategory',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_category', to='products.MainProducts'),
        ),
    ]
