# Generated by Django 2.0.3 on 2018-04-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180318_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscategory',
            name='category',
        ),
        migrations.AddField(
            model_name='mainproducts',
            name='category',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='category', to='products.ProductsCategory'),
        ),
        migrations.AlterField(
            model_name='mainproducts',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mainproducts',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
